# Generated by Django 4.2 on 2024-07-09 12:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_letter_mail', models.IntegerField()),
                ('msg_time_send', models.CharField(max_length=255)),
                ('msg_time_got', models.CharField(max_length=255)),
                ('return_email_path', models.CharField(max_length=255)),
                ('theme', models.CharField(max_length=255)),
                ('to', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('attachments', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=''), null=True, size=None)),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
                'db_table': 'MailLetter',
            },
        ),
    ]
